name: Wiki Content Updated Webhook

on:
  repository_dispatch:
    types: [wiki-updated]

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi
        
      - name: Sync content from wiki
        run: node sync-content.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
        
      - name: Check for changes
        id: changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Detected changes in wiki content"
            git status --porcelain
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi
          
      - name: Commit and push changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/content/docs/
          git commit -m "🔄 Wiki content updated via webhook

          Updated from: ${{ github.event.client_payload.repository }}
          Triggered by: ${{ github.event.client_payload.sender.login }}
          
          🤖 Generated with GitHub Actions
          
          Co-Authored-By: GitHub Action <action@github.com>"
          git push
          
      - name: Trigger deployment
        if: steps.changes.outputs.changes == 'true'
        run: |
          echo "Content updated, deployment will be triggered automatically"